apiVersion: v1
kind: Secret
metadata:
  name: system-under-test
  namespace: benk
stringData:
  serviceName: $(sutServiceName)
  servicePort: "8080"
  backend: $(sutBackendIP)
  username: $(sutUsername)
  password: $(sutPassword)
